### PR TITLE
fix #2: server_dbhost allows for remote database but role does not fully support setting up on remote db

### LINKED ISSUE #2: server_dbhost allows for remote database but role does not fully support setting up on remote db
The server_dbhost var defaults to localhost, and seems to possibly be used to set up the database on a separate host.

The db specific tasks however, do no all use this parameter, especially the database and user creation tasks.

### PR DESCRIPTION
**Pull request by lhoss**
delegate_to to the rescue !
I'm not sure if I missed anything, but the fix worked in our case, with postgres on a different host.

Update: @dj-wasabi I fixed my initial PR. Should be good to merge now!

### CODE REVIEW

**Comment by lhoss** [comment]
Indeed @srvg , sry for the too fast PR  (that just worked for the 'non localhost' case).
I now committed a proper fix, tested for both cases!

ps: I used below debug cmd to ensure the set_fact did the right thing:
- debug: var=delegated_dbhost

ps2: I finally was happy to get it working with one set_fact  thx to googling for the ternary op: http://stackoverflow.com/questions/14214942/python-jinja2-shorthand-conditional
after the initial finding on: https://groups.google.com/forum/#!topic/ansible-project/EKwk210Iy3M

**Comment by dj-wasabi** [comment]
So safe to merge @srvg & @lhoss ?

**Comment by srvg** [comment]
from *looking* at the patch, LGTM, but I have no possibility to effectively test this out atm.

**Comment by lhoss** [comment]
I verified that both cases work (and the remote one works in production :)
so LGTM

**Comment by dj-wasabi** [comment]
Ok. Thanks!

**Pull request merged**
