### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by srvg**
- fix some default vars names that were renamed in the tasks
- simplify evaluation syntax of boolean vars
- various fixes to the postgresql tasks, needed to make it work for me

This last one needs review; I might be missing other use cases than mine. This was tested on Ubuntu 14.04

I used ansible 1.8.2 here.

### CODE REVIEW

**Comment by dj-wasabi** [comment]
Hi Serge,

Due to ilness I wasn't able to test it. Will do this tonight.
Thanks for this pull request!

Kind regards,
Werner

**Comment by srvg** [comment]
I added another commit to fix the location of the webfrontend configuration file.
Without this, after installation, the frontend still redirects to /setup.php and one had to fill in the details manually.

I checked several packages from the upstream Zabbix repo's, and AFAICS, they all use that file location:

```
zabbix-frontend-php_1.8.22-1_all.deb
drwxr-xr-x root/root         0 2015-02-25 03:43 ./etc/
drwxr-xr-x root/root         0 2015-02-25 03:43 ./etc/zabbix/
-rw-r--r-- root/root      1150 2015-02-25 03:43 ./etc/zabbix/apache.conf
drwxr-xr-x root/root         0 2015-02-25 03:43 ./etc/zabbix/web/
lrwxrwxrwx root/root         0 2015-02-25 03:43 ./usr/share/zabbix/conf/zabbix.conf.php -> /etc/zabbix/web/zabbix.conf.php
zabbix-frontend-php_2.0.14-1_all.deb
drwxr-xr-x root/root         0 2015-02-25 03:43 ./etc/
drwxr-xr-x root/root         0 2015-02-25 03:43 ./etc/zabbix/
-rw-r--r-- root/root      1150 2015-02-25 03:43 ./etc/zabbix/apache.conf
drwxr-xr-x root/root         0 2015-02-25 03:43 ./etc/zabbix/web/
lrwxrwxrwx root/root         0 2015-02-25 03:43 ./usr/share/zabbix/conf/zabbix.conf.php -> /etc/zabbix/web/zabbix.conf.php
zabbix-frontend-php_2.2.8-1+trusty_all.deb
drwxr-xr-x root/root         0 2015-02-25 03:43 ./etc/
drwxr-xr-x root/root         0 2015-02-25 03:43 ./etc/zabbix/
-rw-r--r-- root/root      1150 2015-02-25 03:43 ./etc/zabbix/apache.conf
drwxr-xr-x root/root         0 2015-02-25 03:43 ./etc/zabbix/web/
lrwxrwxrwx root/root         0 2015-02-25 03:43 ./usr/share/zabbix/conf/zabbix.conf.php -> /etc/zabbix/web/zabbix.conf.php
zabbix-frontend-php_2.4.4-1+trusty_all.deb
drwxr-xr-x root/root         0 2015-02-25 03:43 ./etc/
drwxr-xr-x root/root         0 2015-02-25 03:43 ./etc/zabbix/
-rw-r--r-- root/root      1150 2015-02-25 03:43 ./etc/zabbix/apache.conf
drwxr-xr-x root/root         0 2015-02-25 03:43 ./etc/zabbix/web/
lrwxrwxrwx root/root         0 2015-02-25 03:43 ./usr/share/zabbix/conf/zabbix.conf.php -> /etc/zabbix/web/zabbix.conf.php

$ rpm -qpl zabbix-web-2.0.14-1.el5.x86_64.rpm | grep etc
/etc/httpd/conf.d/zabbix.conf
/etc/zabbix/web
/etc/zabbix/web/maintenance.inc.php
/etc/zabbix/web/zabbix.conf.php
```

**Comment by dj-wasabi** [comment]
Hi Serge,

Almost everything works, but I had to change the postgresql.yml package installation (1st task) to the following:

```
- name: "PostgreSQL | Debian | Install Ansible module dependencies"
  apt: name=python-psycopg2
       state=present
  when: zabbix_database_creation == True and ansible_os_family == "Debian"

- name: "PostgreSQL | RedHat | Install Ansible module dependencies"
  yum: name=python-psycopg2
       state=present
  when: zabbix_database_creation == True and ansible_os_family == "RedHat"
```

As your version only works on non RedTat operating systems. :-)
Is it an possibility to change it? Otherwise I can do it myself.

Kind regards,
Werner

**Comment by srvg** [comment]
Oops. Totally overlooked that one. Sorry! Will update the PR.

**Comment by srvg** [comment]
I added those tasks in Debian/Redhat.yml and cleaned up my commits. Forced rebase.

**Comment by dj-wasabi** [comment]
Many thanks!

**Pull request merged**
