### PR TITLE
Install Python bindings based on interpreter; Closes dj-wasabi/ansible-zabbix-server#148

### PR DESCRIPTION
**Pull request by kr4ut**
**Description of PR**
Abstracts the package prefix for Python on Debian to a variable that gets calculated before.

**Type of change**
Bugfix Pull Request

**Fixes an issue**
https://github.com/dj-wasabi/ansible-zabbix-server/issues/148

### CODE REVIEW

**Comment by dj-wasabi** [comment]
Hi @kr4ut 

Sorry for late reply.
The CI test is failing, can you please take a look and fix it?

Thank you!

**Comment by kr4ut** [comment]
@dj-wasabi Don't worry about late actually perfectly in time as we started working on revamping our Zabbix infrastructure from today and improving the role internally. But still some prep for more PRs a head and facing a similiar need in ansible-zabbix-web with the whole thingy about: https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.8.html#python-interpreter-discovery

Guess it fails here as this change is not backward compatible and v2.7 is used in Travis. But needs more review how to solve python vs python3 package selection based on the used interpreter. We ported our stuff already to the future default "auto" and needed this change. But will look those days into it if no one still on <= 2.7 is quicker ...

**Comment by kr4ut** [comment]
@dj-wasabi  Wrong assumption on my side it was actually the set_fact and shell module combination. Please double check but assume this fix doesn't change but keep lint happy.

**Comment by dj-wasabi** [comment]
Thanks! 👍

**Pull request merged**
