### PR TITLE
debian and ubuntu repository install was generalized

### PR DESCRIPTION
**Pull request by matheuscunha**
Code clean up and generalizate of Debian/Ubuntu provision

### CODE REVIEW

**Comment by lhoss** [comment]
IMO good to reduce boilerplate (by better abstraction) 👍 
just plz re-add the `tags` element (so it should be functionnaly identical, and have good change for a merge!)

**Comment by matheuscunha** [comment]
Of course. But I didn't remove the tags. It's there:

>  [...]
 with_items:
    - deb-src
    - deb
  tags:
    - zabbix-server
    - init
    - config

**Comment by lhoss** [comment]
sorry @matheuscunha! of course they are still there (lines 54-56 on the left side in compare view) 👍 
good then IMO (assuming you tested with both debian, ubuntu)
but I'm not the maintainer, just a user&contributor (see also latest useful PR of my co-worker colleague :)

**Comment by dj-wasabi** [comment]
p.s. I'll try to fix the CI test today and when fixed, i'll merge the PR.

**Pull request merged**
