### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mklvr**
The zabbix_server_database_creation variable doesn't exist. This needs to be zabbix_database_creation.

**Description of PR**
Documentation correction.

**Type of change**
Docs Pull Request

### CODE REVIEW

**Comment by dj-wasabi** [comment]
Thanks! 👍

**Comment by mklvr** [comment]
I also noticed that zabbix_server_database_sqlload should be zabbix_database_sqlload. There may be others. When I have more time I see if I can create a PR with all the documentation fixes.

**Comment by dj-wasabi** [comment]
Hi @mklvr Ok, thanks! I was just thinking if this name shouldn't conflict with the zabbix-proxy role. As both have the possibility to not load the sqlfiles. Both have the `zabbix_database_creation` property, I'm not sure if this would be ok.

Do you by chance have also a proxy running (and if so, configured with the Ansible role) and do you want to be able to have 1 property or 2, 1 for the server and 1 for the proxy?

**Comment by mklvr** [comment]
I'm not currently using the proxy role, but perhaps it would be better to leave the prefix for these variables as zabbix_server_* and then just make sure the role actually checks those variables. 

However, if the variables were to overlap between the server and playbook roles it wouldn't be that big of a deal, I imagine, since different values can be specified at the playbook level.

**Pull request merged**
