### PR TITLE
tasks/mysql.yml - [add] install mysql client on RHEL base 7

### PR DESCRIPTION
**Pull request by clopnis**
hi,

I thinks it could be good to be sure mysql client is installed.

Regards,
Cyril

### CODE REVIEW

**Comment by clopnis** [comment]
I changed in good place installation of mysql client. Is used to load the zabbix database.

**Comment by dj-wasabi** [comment]
Hi Clopnis,

Thank you for making time to create this Pull Request. 
I believe MySQL will be installed with the mysql role, so what are the benefits by installing in the zabbix playbook?

Kind regards,
Werner

**Comment by clopnis** [comment]
Hi Werner,

MySQL server is not mandatory on Zabbix server. Typically in my case, i'm using an external SQL cluster.

Regards,

Cyril

**Comment by dj-wasabi** [comment]
Hi Cyril,

You are absolutely right, my bad. Will accept it.

Kind regards,
Werner

**Pull request merged**
